import { build } from 'vite'
import vue from '@vitejs/plugin-vue'
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync, readdirSync, unlinkSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

// NOTE: Bundles are compiled as IIFE with vue as external.
// The host app (admin) must expose window.Vue before loading widget scripts.
// See: useCustomWidgetLoader.ts → exposeVueGlobal()

const __dirname = dirname(fileURLToPath(import.meta.url))
const distDir = resolve(__dirname, 'dist')

// 1. Read and validate manifest
const manifestPath = resolve(__dirname, 'src/manifest.json')
if (!existsSync(manifestPath)) {
  console.error('ERROR: src/manifest.json not found')
  process.exit(1)
}
const manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'))
if (!manifest.name || !manifest.fields) {
  console.error('ERROR: manifest.json must have "name" and "fields"')
  process.exit(1)
}

const widgetName = manifest.name
const globalName = `__HAVIX_WIDGET_${widgetName.replace(/-/g, '_').toUpperCase()}`

console.log(`\nBuilding widget: ${widgetName} (v${manifest.version || '1.0.0'})\n`)

mkdirSync(distDir, { recursive: true })

// 2. Build render.js
console.log('Compiling Render.vue → render.js ...')
await build({
  configFile: false,
  plugins: [vue()],
  root: __dirname,
  build: {
    outDir: 'dist',
    emptyOutDir: false,
    lib: {
      entry: resolve(__dirname, 'src/Render.vue'),
      formats: ['iife'],
      name: globalName,
      fileName: () => 'render.js'
    },
    rollupOptions: {
      external: ['vue'],
      output: {
        globals: { vue: 'Vue' },
        footer: `(function(){window.__HAVIX_WIDGETS__=window.__HAVIX_WIDGETS__||{};window.__HAVIX_WIDGETS__["${widgetName}"]={render:${globalName}};})();`
      }
    },
    minify: true
  },
  logLevel: 'warn'
})

// 3. Build preview.js
const previewPath = resolve(__dirname, 'src/Preview.vue')
if (existsSync(previewPath)) {
  console.log('Compiling Preview.vue → preview.js ...')
  const previewGlobal = `${globalName}_PREVIEW`
  await build({
    configFile: false,
    plugins: [vue()],
    root: __dirname,
    build: {
      outDir: 'dist',
      emptyOutDir: false,
      lib: {
        entry: previewPath,
        formats: ['iife'],
        name: previewGlobal,
        fileName: () => 'preview.js'
      },
      rollupOptions: {
        external: ['vue'],
        output: {
          globals: { vue: 'Vue' },
          footer: `(function(){window.__HAVIX_WIDGETS__=window.__HAVIX_WIDGETS__||{};if(!window.__HAVIX_WIDGETS__["${widgetName}"])window.__HAVIX_WIDGETS__["${widgetName}"]={};window.__HAVIX_WIDGETS__["${widgetName}"].preview=${previewGlobal};})();`
        }
      },
      minify: true
    },
    logLevel: 'warn'
  })
} else {
  console.log('No Preview.vue found, skipping preview build.')
}

// 4. Copy manifest
console.log('Copying manifest.json ...')
copyFileSync(manifestPath, resolve(distDir, 'manifest.json'))

// 5. Merge CSS: src/style.css + any CSS files generated by Vite from <style> blocks
console.log('Merging CSS ...')
const distStylePath = resolve(distDir, 'style.css')
const srcStylePath  = resolve(__dirname, 'src/style.css')

let mergedCss = existsSync(srcStylePath) ? readFileSync(srcStylePath, 'utf-8') : ''

// Find CSS files that Vite extracted from SFC <style> blocks (anything except style.css)
const extraCss = readdirSync(distDir).filter(f => f.endsWith('.css') && f !== 'style.css')
for (const f of extraCss) {
  const p = resolve(distDir, f)
  mergedCss += '\n' + readFileSync(p, 'utf-8')
  unlinkSync(p)
}

if (mergedCss.trim()) {
  writeFileSync(distStylePath, mergedCss)
  console.log(`style.css written (${(mergedCss.length / 1024).toFixed(1)} KB)`)
}

// 5. Create ZIP bundle
console.log('Creating bundle ZIP ...')
const archiver = (await import('archiver')).default
const { createWriteStream } = await import('fs')

const zipPath = resolve(distDir, 'widget-bundle.zip')
const output = createWriteStream(zipPath)
const archive = archiver('zip', { zlib: { level: 9 } })

await new Promise((resolvePromise, reject) => {
  output.on('close', resolvePromise)
  archive.on('error', reject)
  archive.pipe(output)

  archive.file(resolve(distDir, 'manifest.json'), { name: 'manifest.json' })
  archive.file(resolve(distDir, 'render.js'), { name: 'render.js' })
  if (existsSync(resolve(distDir, 'preview.js'))) {
    archive.file(resolve(distDir, 'preview.js'), { name: 'preview.js' })
  }
  if (existsSync(resolve(distDir, 'style.css'))) {
    archive.file(resolve(distDir, 'style.css'), { name: 'style.css' })
  }

  archive.finalize()
})

console.log(`\nBundle pronto! Faca upload do arquivo:`)
console.log(`  dist/widget-bundle.zip\n`)
console.log(`No painel admin: Storefront > Custom Widgets > Upload`)
